name: Local
values:
  - key: baseUrl
    value: 'http://localhost:8080'
    enabled: true
  - key: profileSlug
    value: ''
    enabled: true
  - key: albumId
    value: ''
    enabled: true
  - key: photoId
    value: ''
    enabled: true
  - key: featureType
    value: HOMEPAGE_GRID
    enabled: true
  - key: featureIndex
    value: '0'
    enabled: true
  - key: featureEnabled
    value: 'true'
    enabled: true
  - key: lastFeatureIndex
    value: ''
    enabled: true
  - key: email
    value: sate3.mallouhi@gmail.com
    enabled: true
  - key: password
    value: '00000000'
    enabled: true
