spring:
  application:
    name: backend

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "849153694603-rsb2si66hi2vu6cqpftu7tffdrhsmlif.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - openid
              - profile
              - email

  datasource:
    url: jdbc:postgresql://localhost:5432/photo_gallery
    username: photo
    password: photo

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: sate3.mallouh@gmail.com
    password: ngvd kldz xjjx viop
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  frontend:
    base-url: http://localhost:5173
  storage:
    type: local
    local:
      root-path: ./storage
