spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/photo_gallery
    username: photo
    password: photo

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: sate3.mallouh@gmail.com
    password: ngvd kldz xjjx viop
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  storage:
    type: local
    local:
      root-path: ./storage
